----
---- Release 0.1
---- Jean-PHilippe Breysse
----

drop table servicesiaas cascade constraints; 

create table servicesiaas (
    id                             number generated by default on null as identity 
                                   constraint service_id_pk primary key,
    name                           varchar2(30 char)
);


drop table vm_conso cascade constraints ;

create table vm_conso (
    id                             number generated by default on null as identity 
                                   constraint vm_id_pk primary key,
    iaas_id                        number 
                                   constraints iaas_hq_fq references servicesiaas on delete cascade,                               
    name                           varchar2(30 char),
    cpu_usage                      number,
    conso_number                   number,
    vcpu_num                       number
)
;

---
---
---

drop table country_green cascade constraints;

create table country_green (
    id              number generated by default on null as identity 
                    constraint countrygreen_id_pk primary key,
    country_name    varchar2(80)
)
;


drop table data_center;


create table data_center (
    id                             number generated by default on null as identity 
                                   constraint dc_test_id_pk primary key,
    country_id                     number constraints dc_country_fK
                                   references country_green on delete cascade,                             
    dc_name                        varchar2(80 char)
)                      
;


drop table country_carbon_density cascade constraints ;

create table country_carbon_density(
    country_id          number,               
    date_consumption    date,
    constraint country_carbon_pk primary key(country_id, date_consumption),
    carbon_density_kwh number
);

alter table country_carbon_density add constraint country_carbon_pk primary key(country_id, date_consumption)
;

alter table country_carbon_density 
    add constraint country_carbon_fk
    foreign key(country_id)
    references country_green(id)
;

---
--- ecommerce, app
---  content managment 
--- 


drop table application_type;

create table application_type(
    id   number generated by default on null as identity 
                                   constraint app_type_id_pk primary key,
    app_type_name                  varchar2(80)
);


drop table application cascade constraints;


create table application (
    id                             number generated by default on null as identity 
                                   constraint app_id_pk primary key,
    wk_name                         varchar2(100 char),
    wl_type                         varchar2(100)
)
;


---
--- workload baseline
---
---
--- app1, baseline, 1000 users
---- app1, baseline2, 2000 users


drop table app_workload_baseline cascade constraints;

create  table app_workload_baseline (
    id                             number generated by default on null as identity 
                                   constraint app_wk_bsale_id_pk primary key,                           
    wkb_id                         number constraints wk_app_hq_fq
                                   references application on delete cascade,
    wka_name                       varchar2(40 char),
    transaction_number              NUMBER,
    end_users                       number,
    metrics1                        number
);





drop table app_architecture cascade constraints;
---   reference app_ worklaod
----  Pk: id + app_worload
----- baseline, 1 app server, 2 vcpu, 
----- baseline, 1 db server, 2vcpu
---- 

create table app_architecture (
    id                             number generated by default on null as identity 
                                   constraint app_a_id_pk primary key,                           
    appw_id                        number 
                                   constraints app_a_baseline_hq_fq references app_workload_baseline on delete cascade,
    ar_name                        varchar2(40 char),
    vm_type                        VARCHAR2(80),
    vm_size                        number,
    cpu_usage                      number
)
;




--
-- PK: appworkload_id, data_center_id
-- energy: calaculation using 
---  baseline 1; Paris,  300 W, 
---


drop table app_co2_consumption cascade constraints;

create table app_co2_consumption 
(                                         
    app_workload_baseline_id         number, 
    data_center_id                   number,
    energy                          number,
    carbon_emission                 number
)
;


alter table app_co2_consumption add constraint app_carbon_pk primary key(app_workload_baseline_id, data_center_id);


alter table app_co2_consumption add constraint app_co2_con_fk foreign key(APP_WORKLOAD_Baseline_ID)
references app_workload_baseline;


alter table app_co2_consumption add constraint app_co2_con2_fk foreign key(data_center_ID)
references data_center;
